
project_id = "ceinvnueokxhrlwngfny"

[api]
# Typically this value is the same as the value of project_id
# If omitted, CI jobs will use the value of project_id to make API requests
id = "ceinvnueokxhrlwngfny"

[[functions]]
name = "mailchimp-subscribe"

[[functions]]
name = "send-scheduled-emails"

[[functions]]
name = "generate-industry-content"

[[functions]]
name = "stripe-subscription"

[[functions]]
name = "stripe-webhook"
