
project_id = "ceinvnueokxhrlwngfny"

[functions]
[functions.mailchimp-subscribe]

[functions.send-scheduled-emails]

[functions.generate-industry-content]

[functions.stripe-subscription]

[functions.stripe-webhook]
