// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceinvnueokxhrlwngfny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaW52bnVlb2t4aHJsd25nZm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTI0NDEsImV4cCI6MjA1NTM2ODQ0MX0.TAIkxPACdwDx2_k8b6GrOVCUXn9oCJ-QtIfWTyAjZCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);